### ISSUE TITLE
0.67 interpolation_exponent in y dimension cases error

### ISSUE THREAD

**Issue by tevpg** [tevpg/data_colors#2]
For certain values of interpolation_exponent for second dimension of 2D ColorFactory, get an UnboundLocalVariable error.

I have note been able to make it happen on the first dimension, only the second.  Values that cause the error include 0.67, 0.68, 1.5

```
exp   min   max
0.67    0   100   -> error
0.67    0   200   -> ok
1.25    0   100   -> error
1.25    0   200   -> error
1.25    0   230   -> ok
```

I believe this happens on the very first call to css_bg(), at which points (x,y) values are (0,{max})

Sample ColorFactory:
```
ColorFactory <data_colors.ColorFactory object at 0x7f51b29b3fd0>
  ready: True; dimensions: 2; blend method: multiplicative
  Dimension 0:
    ready: True; configs: 2; min/max/range: 0.0/100.0/100.0; interpolation_exponent: 1
      ConfigPoint 0:    0.00;  rgb(255,255,255) --> white
      ConfigPoint 1:  100.00;  rgb(255,99,71)   --> tomato
  Dimension 1:
    ready: True; configs: 2; min/max/range: 0.0/100.0/100.0; interpolation_exponent: 0.67
      ConfigPoint 0:    0.00;  rgb(255,255,255) --> white
      ConfigPoint 1:  100.00;  rgb(123,104,238) --> mediumslateblue
```

Error output:
```
Traceback (most recent call last):
  File "/fs/sysbits/tagtracker/datacolors/colortable.py", line 209, in <module>
    print(make_html_color_table(cf))
  File "/fs/sysbits/tagtracker/datacolors/colortable.py", line 143, in make_html_color_table
    html.add(cell(factory,x_index,y_index))
  File "/fs/sysbits/tagtracker/datacolors/colortable.py", line 135, in cell
    return f"<td style={cf.css_bg((x_index,y_index))}></td>"
  File "/fs/sysbits/tagtracker/datacolors/data_colors.py", line 568, in css_bg
    bg = self.get_color(*determiner)
  File "/fs/sysbits/tagtracker/datacolors/data_colors.py", line 532, in get_color
    return self._cached_get_color(determiner_tuple)
  File "/fs/sysbits/tagtracker/datacolors/data_colors.py", line 548, in _cached_get_color
    colors_list.append(dimension.get_color(determiner_tuple[i]))
  File "/fs/sysbits/tagtracker/datacolors/data_colors.py", line 464, in get_color
    if gradient_min.real == gradient_max.real:
UnboundLocalError: local variable 'gradient_min' referenced before assignment
```

**Comment by tevpg** [comment]
Adjusting the determiner by exponent could sometimes make the adjusted determiner outside the Dimension's range, resulting in an unknowable gradient selection. Solved by clamping the adjusted determiner to the Dimension's range.
